print("What is your name?")
name = input()
print("What job are you training for?")
job = input()
print("What negative emotion do you feel about the cohort in one word adjective form?")
adjective_a = input()
print("How would you positively describe your teacher in one word adjective form?")
adjective_b = input()
print("What was your main course for lunch today in one word form?")
lunch = input()
print("What did you have with your main course today in one word form?")
drink = input()
print("How are you feeling in one word present tense?")
feeling = input()
print(name + " started their first Generation course today. They are training as a " + job + ". They found their cohort to be very " + adjective_a + " but their teacher was, at least, "+ adjective_b + ". For lunch they have "+ lunch + " and " + drink + " while reviewing their notes. They feel " + feeling + " but are determined to complete the course.")
